require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'Yogurt' do
  
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod "SquareInAppPaymentsSDK"
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNSquareInAppPayments', :path => '../node_modules/react-native-square-in-app-payments'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  target 'YogurtTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Yogurt-tvOS' do
  # Pods for Yogurt-tvOS

  target 'Yogurt-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
